// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakeHomeAPI.Data;

#nullable disable

namespace TakeHomeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250410080429_UpdateSchemaForProductsPackagingItems")]
    partial class UpdateSchemaForProductsPackagingItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakeHomeAPI.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PackagingID")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("PackagingID")
                        .HasDatabaseName("IDX_Item_PackagingID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Packaging", b =>
                {
                    b.Property<int>("PackagingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackagingID"));

                    b.Property<string>("PackagingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentPackagingID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("PackagingID");

                    b.HasIndex("ParentPackagingID")
                        .HasDatabaseName("IDX_Packaging_ParentPackagingID");

                    b.HasIndex("ProductID")
                        .HasDatabaseName("IDX_Packaging_ProductID");

                    b.ToTable("Packagings");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Item", b =>
                {
                    b.HasOne("TakeHomeAPI.Models.Packaging", "Packaging")
                        .WithMany("Items")
                        .HasForeignKey("PackagingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packaging");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Packaging", b =>
                {
                    b.HasOne("TakeHomeAPI.Models.Packaging", "ParentPackaging")
                        .WithMany("ChildPackagings")
                        .HasForeignKey("ParentPackagingID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TakeHomeAPI.Models.Product", "Product")
                        .WithMany("Packagings")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentPackaging");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Packaging", b =>
                {
                    b.Navigation("ChildPackagings");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Product", b =>
                {
                    b.Navigation("Packagings");
                });
#pragma warning restore 612, 618
        }
    }
}
