// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakeHomeAPI.Data;

#nullable disable

namespace TakeHomeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250409094842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakeHomeAPI.Models.Packaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentPackagingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentPackagingId");

                    b.ToTable("Packagings");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PackagingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackagingId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Packaging", b =>
                {
                    b.HasOne("TakeHomeAPI.Models.Packaging", "ParentPackaging")
                        .WithMany("ChildPackagings")
                        .HasForeignKey("ParentPackagingId");

                    b.Navigation("ParentPackaging");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Product", b =>
                {
                    b.HasOne("TakeHomeAPI.Models.Packaging", "Packaging")
                        .WithMany()
                        .HasForeignKey("PackagingId");

                    b.Navigation("Packaging");
                });

            modelBuilder.Entity("TakeHomeAPI.Models.Packaging", b =>
                {
                    b.Navigation("ChildPackagings");
                });
#pragma warning restore 612, 618
        }
    }
}
